version: "3.9"
#rabbitmq-plugins list
#rabbitmq-plugins enable rabbitmq_stomp
#rabbitmq-plugins enable rabbitmq_web_stomp
services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - 15672:15672
      - 5672:5672
      - 61613:61613