server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: 'test-client'
          client-secret: 'test-client'
          custom-auth: true

  main:
    allow-bean-definition-overriding: true
  application:
    name: qr-b2b-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
gateway:
  logger: true