spring:
  application:
    name: qr-b2b-service
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8001
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      default:
        group: qr-b2b-service
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093

qr-cache:
  enabled: ${QR_CACHE_ENABLED:true}
  redis:
    server:
      host: ${QR_REDIS_SERVER_HOST:localhost}
      port: ${QR_REDIS_SERVER_PORT:6385}
      user: ${QR_REDIS_SERVER_USER:user}
      password: ${QR_REDIS_SERVER_PASSWORD:password}

