version: "3.9"

services:
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6385:6379"
    networks:
      - search-network
      - qr-b2b-infrastructure-network

networks:
  qr-b2b-infrastructure-network:
    name: qr-b2b-infrastructure-network
    driver: bridge
  search-network:
    external: true
    name: data-search-network
